### ISSUE TITLE
Fun graphical effects

### ISSUE THREAD

**Issue by dascritch** [cpuprogramme/cpu-15#37]
It may be funny and friendly to put some effects as this one : 
https://atomiks.github.io/30-seconds-of-css/#mouse-cursor-gradient-tracking

**Comment by dascritch** [comment]
gadget :P

**Comment by dascritch** [comment]
invert(100%) hue-rotate(180deg).
keeping it for konami code

**Comment by dascritch** [comment]
Better to remove any <a> inside <article> then css it :+1: 
```css
a:hover article, a:focus article{
filter : invert(100%) hue-rotate(180deg);
transition : 0.2s;
}

a:hover article .calque, , a:focus article .calque {
background : white;
}
```

But we will have problems with the audio player :/
