### ISSUE TITLE
Enhance role=navigation

### ISSUE THREAD

**Issue by dascritch** [cpuprogramme/cpu-15#71]
<https://github.com/GoogleChrome/lighthouse/issues/12761>

`<nav role="navigation">` : 
- `role="navigation"` is implicit
- this `<nav>` should be ID'd , to visibly hide (and not `display : none`) only on the ID
- `<ul role="navigation">` should be `<nav><ul>`

**Comment by dascritch** [comment]
```css
#skip-links {
  height: 0px;
  overflow: hidden;
}

#skip-links:focus-within {
  height: auto;

}

/* remove .skip-links a  */

```
